# Generated by Django 4.2 on 2023-07-20 19:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Categorie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=100, verbose_name="Nom")),
            ],
            options={
                "verbose_name": "Categorie",
                "verbose_name_plural": "Categories",
            },
        ),
        migrations.CreateModel(
            name="SupplyHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reference",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Référence"
                    ),
                ),
                (
                    "designation",
                    models.CharField(
                        help_text="Nom de l'item",
                        max_length=150,
                        verbose_name="Désignation",
                    ),
                ),
                (
                    "quantite",
                    models.IntegerField(
                        blank=True, default=0, null=True, verbose_name="Quantité"
                    ),
                ),
                (
                    "prix_unitaire",
                    models.IntegerField(
                        blank=True, default=0, null=True, verbose_name="Prix unitaire"
                    ),
                ),
                (
                    "quantite_recu",
                    models.IntegerField(
                        blank=True, default=0, null=True, verbose_name="Quantité réçu"
                    ),
                ),
                (
                    "provient_de",
                    models.CharField(
                        blank=True,
                        max_length=150,
                        null=True,
                        verbose_name="Provient de",
                    ),
                ),
                (
                    "date_creation",
                    models.DateTimeField(null=True, verbose_name="Date de création"),
                ),
                (
                    "date_mise_a_jour",
                    models.DateTimeField(null=True, verbose_name="Date de mise à jour"),
                ),
                (
                    "categorie",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="products.categorie",
                    ),
                ),
            ],
            options={
                "verbose_name": "Historique D'approvisionnement ",
                "verbose_name_plural": "Historique D'approvisionnements",
                "ordering": ["-date_mise_a_jour"],
            },
        ),
        migrations.CreateModel(
            name="Stock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reference",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Référence"
                    ),
                ),
                (
                    "designation",
                    models.CharField(
                        blank=True,
                        help_text="Nom de l'item",
                        max_length=150,
                        null=True,
                        verbose_name="Désignation",
                    ),
                ),
                (
                    "quantite",
                    models.IntegerField(
                        blank=True, default=0, null=True, verbose_name="Quantité"
                    ),
                ),
                (
                    "prix_achat",
                    models.PositiveIntegerField(
                        blank=True, default=0, null=True, verbose_name="Prix d'achat"
                    ),
                ),
                (
                    "prix_vente",
                    models.IntegerField(default=0, verbose_name="Prix de vente"),
                ),
                (
                    "pourcentage",
                    models.PositiveIntegerField(
                        blank=True, default=0, null=True, verbose_name="Pourcentage"
                    ),
                ),
                (
                    "seuil_alert",
                    models.IntegerField(
                        blank=True, default=0, null=True, verbose_name="Seuil d'alert"
                    ),
                ),
                (
                    "recevoir_quantite",
                    models.IntegerField(
                        blank=True,
                        default=0,
                        null=True,
                        verbose_name="Récevoir une quantité",
                    ),
                ),
                (
                    "recu_par",
                    models.CharField(
                        blank=True, max_length=150, null=True, verbose_name="Réçu par"
                    ),
                ),
                (
                    "delivre_quantite",
                    models.IntegerField(
                        blank=True,
                        default=0,
                        null=True,
                        verbose_name="Délivrer une quantité",
                    ),
                ),
                (
                    "delivre_par",
                    models.CharField(
                        blank=True,
                        max_length=150,
                        null=True,
                        verbose_name="Délivré par",
                    ),
                ),
                (
                    "delivre_a",
                    models.CharField(
                        blank=True, max_length=150, null=True, verbose_name="Délivré à"
                    ),
                ),
                (
                    "date_creation",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "date_mise_a_jour",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de mise à jour"
                    ),
                ),
                (
                    "categorie",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="products.categorie",
                    ),
                ),
            ],
            options={
                "verbose_name": "Stock",
                "verbose_name_plural": "Stocks",
                "ordering": ["-date_creation"],
            },
        ),
        migrations.CreateModel(
            name="SaleHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reference",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Référence"
                    ),
                ),
                (
                    "designation",
                    models.CharField(
                        help_text="Nom de l'item",
                        max_length=150,
                        verbose_name="Désignation",
                    ),
                ),
                (
                    "quantite",
                    models.IntegerField(
                        blank=True, default=0, null=True, verbose_name="Quantité"
                    ),
                ),
                (
                    "prix_unitaire",
                    models.IntegerField(
                        blank=True, default=0, null=True, verbose_name="Prix unitaire"
                    ),
                ),
                (
                    "quantite_vendu",
                    models.IntegerField(
                        blank=True,
                        default=0,
                        null=True,
                        verbose_name="Quantité délivrée",
                    ),
                ),
                (
                    "delivre_par",
                    models.CharField(
                        blank=True,
                        max_length=150,
                        null=True,
                        verbose_name="Délivré par",
                    ),
                ),
                (
                    "delivre_a",
                    models.CharField(
                        blank=True, max_length=150, null=True, verbose_name="Délivré à"
                    ),
                ),
                (
                    "date_creation",
                    models.DateTimeField(null=True, verbose_name="Date de création"),
                ),
                (
                    "date_mise_a_jour",
                    models.DateTimeField(null=True, verbose_name="Date de mise à jour"),
                ),
                (
                    "categorie",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="products.categorie",
                    ),
                ),
            ],
            options={
                "verbose_name": "Historique Vente",
                "verbose_name_plural": "Historique Ventes",
                "ordering": ["-date_mise_a_jour"],
            },
        ),
    ]
